modLoader="javafml" #mandatory
loaderVersion="[43,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"

[[mods]] #mandatory
modId="magecraft" #mandatory
version="0.0.1" #mandatory
displayName="Mage Craft" #mandatory
logoFile="examplemod.png" #optional
authors="Olly Holcombe" #optional
description='''
Mage Craft is a small mod that will bring some new features to minecraft.
It is not going to be rapidly built and updated but i will try to.
It will be more endgame focused but there will be uses for it early game.

'''

[[dependencies.magecraft]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[43,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.magecraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
